import type { DetectableTradeKey, TradeKeywordSet } from "@/lib/onboarding/jobDetection/types";

const R = (pattern: string, flags = "i"): RegExp => new RegExp(pattern, flags);

/**
 * Cartographie mots-clés + regex par métier.
 * Ajouter un métier = une entrée ici + `TRADE_TO_METIER_KEY`.
 */
export const JOB_KEYWORD_REGISTRY: Record<DetectableTradeKey, TradeKeywordSet> = {
  ELECTRICIEN: {
    includes: [
      "electricite",
      "electrique",
      "electricien",
      "electric",
      "electrician",
      "cablage",
      "tableau electrique",
      "domotique",
      "installation electrique",
      "depannage electrique",
      "mise aux normes",
      "borne de recharge",
      "irve",
      "photovoltaique",
      "courant faible",
      "gaz electrogene",
    ],
    regexes: [
      R("\\belec\\b"),
      R("\\belectrici"),
      R("\\belectri(c|que|cien)"),
      R("\\bwatt\\b"),
      R("\\bvolt\\b"),
    ],
  },
  PLOMBIER: {
    includes: [
      "plomberie",
      "plombier",
      "plumber",
      "plumbing",
      "fuite",
      "sanitaire",
      "chauffe-eau",
      "chauffe eau",
      "ballon eau chaude",
      "tuyauterie",
      "debouchage",
      "robinetterie",
      "wc",
      "evier",
      "canalisation",
      "degorgement",
    ],
    regexes: [R("\\bplomb"), R("\\bplumb")],
  },
  CHAUFFAGISTE: {
    includes: [
      "chauffagiste",
      "heating",
      "chauffage",
      "pompe a chaleur",
      "pac",
      "chaudiere",
      "climatisation",
      "clim",
      "hvac",
      "radiateur",
      "plancher chauffant",
      "entretien chaudiere",
      "installation pac",
      "split",
      "gainable",
    ],
    regexes: [
      R("\\bpac\\b"),
      R("\\bclim\\b"),
      R("\\bchauffag"),
      R("\\bchaudiere"),
      R("\\bclimatisation"),
    ],
  },
  MACON: {
    includes: [
      "maconnerie",
      "macon",
      "mason",
      "masonry",
      "brique",
      "beton",
      "extension",
      "fondation",
      "gros oeuvre",
      "parpaing",
      "mur porteur",
      "dalle beton",
      "terrasse beton",
      "agrandissement",
    ],
    regexes: [R("\\bmacon"), R("\\bmason"), R("\\bbeton\\b"), R("\\bbrique")],
  },
  PEINTRE: {
    includes: [
      "peinture",
      "peintre",
      "painter",
      "painting",
      "enduit",
      "renovation interieure",
      "tapisserie",
      "finition",
      "ravalement",
      "decoration interieure",
      "lessivage",
      "preparation murs",
    ],
    regexes: [R("\\bpeint"), R("\\bpaint")],
  },
  MENUISIER: {
    includes: [
      "menuiserie",
      "menuisier",
      "carpenter",
      "carpentry",
      "bois",
      "pvc",
      "alu",
      "aluminium",
      "fenetre",
      "porte",
      "parquet",
      "agencement",
      "escalier",
      "veranda",
      "pergola",
      "double vitrage",
      "volet",
      "store",
    ],
    regexes: [
      R("\\bmenuiser"),
      R("\\bmenuisier"),
      R("\\bparquet\\b"),
      R("\\bfenetre"),
      R("\\bporte\\b"),
    ],
  },
};

export const DETECTABLE_TRADE_KEYS = Object.keys(
  JOB_KEYWORD_REGISTRY,
) as DetectableTradeKey[];
